name: tcn-example
channels:
- defaults
dependencies:
- h5py>=2.7.0,<3
- hdf5=1.8
- Keras=2.2
- matplotlib=2
- mkl=2017.0.3
- numpy>=1.12
- pip>=9.0.1,<=18
- python=3.6
- scipy=0.19.1
- zlib=1.2.11
- tensorflow=1.11.0
- pip:
  - black==18.9b0
  - git+https://github.com/maxpumperla/hyperas.git@master
  - joblib==0.12.5
  - keras-tcn==2.3.3
  - scikit-learn==0.20.1
